// Quiet Ledger style reminder: sheets reduce the emotional and cognitive cost of action; every form is short, editable, and explicit about local prototype boundaries.

import { FormEvent, useState } from "react";
import { ArrowUpRight, Check, Copy, FileText, MessageCircle, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { BRAND } from "@/config/brand";
import { addIndiaBusinessDays, formatDate, formatINR, getLatestPromise, getOutstanding, getSuggestion, interpolateMessage, messageTemplates, parseINRToPaise, todayInIndia } from "@/lib/finance";
import type { Client, DemoState, PaymentMethod, PromiseSource, Receivable } from "@/types/domain";
import { Field, Sheet } from "@/components/finance-ui";

const inputClass = "form-input";

export function AddClientSheet({ onClose, onSubmit }: { onClose: () => void; onSubmit: (input: { name: string; company: string; phone: string; email: string; notes: string }) => void }) {
  const [form, setForm] = useState({ name: "", company: "", phone: "", email: "", notes: "" });
  function submit(event: FormEvent) { event.preventDefault(); if (!form.name.trim()) { toast.error("Add a client name before saving."); return; } onSubmit(form); }
  return <Sheet title="Add client" eyebrow="Keep the relationship clear" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button form="add-client-form" className="button-primary">Save client <ArrowUpRight size={16} /></button></>}><form id="add-client-form" className="form-stack" onSubmit={submit}><p className="sheet-intro">A client can come first. Add a receivable when an invoice is ready to follow.</p><div className="form-grid form-grid--two"><Field label="Client name"><input className={inputClass} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Arjun Mehta" required /></Field><Field label="Company" hint="Optional"><input className={inputClass} value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} placeholder="e.g. Nova Media" /></Field></div><div className="form-grid form-grid--two"><Field label="Phone" hint="Optional"><input className={inputClass} inputMode="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="+91" /></Field><Field label="Email" hint="Optional"><input className={inputClass} type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@company.com" /></Field></div><Field label="Note" hint="Optional"><textarea className={`${inputClass} textarea`} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="What should you remember later?" rows={3} /></Field></form></Sheet>;
}

export function AddReceivableSheet({ onClose, onSubmit }: { onClose: () => void; onSubmit: (input: { clientName: string; company: string; receivableLabel: string; amountPaise: number; dueDate: string; invoiceRef: string; phone: string; email: string; notes: string }) => void }) {
  const [form, setForm] = useState({ clientName: "", company: "", receivableLabel: "", amount: "", dueDate: todayInIndia(), invoiceRef: "", phone: "", email: "", notes: "" });
  function submit(event: FormEvent) { event.preventDefault(); const amountPaise = parseINRToPaise(form.amount); if (!form.clientName.trim() || !amountPaise || !form.dueDate) { toast.error("Add a client, valid amount, and due date first."); return; } onSubmit({ clientName: form.clientName, company: form.company, receivableLabel: form.receivableLabel, amountPaise, dueDate: form.dueDate, invoiceRef: form.invoiceRef, phone: form.phone, email: form.email, notes: form.notes }); }
  return <Sheet title="Add receivable" eyebrow="Start after the invoice is already out" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button form="add-receivable-form" className="button-primary">Save receivable <ArrowUpRight size={16} /></button></>}><form id="add-receivable-form" className="form-stack" onSubmit={submit}><p className="sheet-intro">Keep it fast. You only need enough context to remember the next conversation.</p><div className="form-grid form-grid--two"><Field label="Client name"><input className={inputClass} value={form.clientName} onChange={(event) => setForm({ ...form, clientName: event.target.value })} placeholder="e.g. Arjun Mehta" required /></Field><Field label="Company" hint="Optional"><input className={inputClass} value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} placeholder="e.g. Nova Media" /></Field></div><div className="form-grid form-grid--two"><Field label="Amount"><div className="input-prefix"><span>₹</span><input className={inputClass} inputMode="decimal" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} placeholder="28,000" required /></div></Field><Field label="Due date"><input className={inputClass} type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} required /></Field></div><Field label="What is this for?" hint="Optional"><input className={inputClass} value={form.receivableLabel} onChange={(event) => setForm({ ...form, receivableLabel: event.target.value })} placeholder="e.g. August design retainer" /></Field><Field label="Invoice or reference" hint="Optional"><input className={inputClass} value={form.invoiceRef} onChange={(event) => setForm({ ...form, invoiceRef: event.target.value })} placeholder="e.g. NM-042" /></Field><div className="form-grid form-grid--two"><Field label="Phone" hint="Optional"><input className={inputClass} inputMode="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="+91" /></Field><Field label="Email" hint="Optional"><input className={inputClass} type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@company.com" /></Field></div><Field label="Note" hint="Optional"><textarea className={`${inputClass} textarea`} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="What should you remember later?" rows={3} /></Field></form></Sheet>;
}

export function AddPromiseSheet({ receivable, client, state, onClose, onSubmit }: { receivable: Receivable; client?: Client; state: DemoState; onClose: () => void; onSubmit: (input: { amountPaise: number; promisedDate: string; source: PromiseSource; note: string }) => void }) {
  const [form, setForm] = useState({ amount: String(getOutstanding(receivable, state.payments) / 100), promisedDate: todayInIndia(), source: "WhatsApp" as PromiseSource, note: "" });
  function submit(event: FormEvent) { event.preventDefault(); const amountPaise = parseINRToPaise(form.amount); if (!amountPaise || amountPaise > getOutstanding(receivable, state.payments) || !form.promisedDate) { toast.error("Add a valid promise amount within the remaining balance and a date."); return; } onSubmit({ amountPaise, promisedDate: form.promisedDate, source: form.source, note: form.note }); }
  return <Sheet title="Record a new promise" eyebrow={client?.company} onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button form="promise-form" className="button-primary">Keep this promise <Check size={16} /></button></>}><form id="promise-form" className="form-stack" onSubmit={submit}><div className="context-band"><div><span>Still outside</span><strong>{formatINR(getOutstanding(receivable, state.payments))}</strong></div><FileText size={18} /></div><p className="sheet-intro">A new promise adds to the story. It never overwrites what happened before.</p><div className="form-grid form-grid--two"><Field label="Promised amount"><div className="input-prefix"><span>₹</span><input className={inputClass} inputMode="decimal" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} required /></div></Field><Field label="Promised date"><input className={inputClass} type="date" value={form.promisedDate} onChange={(event) => setForm({ ...form, promisedDate: event.target.value })} required /></Field></div><Field label="Source"><select className={inputClass} value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value as PromiseSource })}>{["WhatsApp", "Call", "Email", "Meeting", "Other"].map((source) => <option key={source} value={source}>{source}</option>)}</select></Field><Field label="Note" hint="Optional"><textarea className={`${inputClass} textarea`} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="What did they say?" rows={3} /></Field></form></Sheet>;
}

export function PaymentSheet({ receivable, state, onClose, onSubmit }: { receivable: Receivable; state: DemoState; onClose: () => void; onSubmit: (input: { amountPaise: number; paidDate: string; method: PaymentMethod; reference: string }) => void }) {
  const [form, setForm] = useState({ amount: String(getOutstanding(receivable, state.payments) / 100), paidDate: todayInIndia(), method: "UPI" as PaymentMethod, reference: "" });
  const outstanding = getOutstanding(receivable, state.payments);
  const enteredAmountPaise = parseINRToPaise(form.amount) ?? 0;
  const remainingAfter = Math.max(0, outstanding - enteredAmountPaise);
  function submit(event: FormEvent) { event.preventDefault(); const amountPaise = parseINRToPaise(form.amount); if (!amountPaise) { toast.error("Add a valid payment amount first."); return; } if (amountPaise > outstanding) { toast.error("A payment cannot be more than the remaining balance."); return; } onSubmit({ amountPaise, paidDate: form.paidDate, method: form.method, reference: form.reference }); }
  return <Sheet title="Record payment" eyebrow="Update the money story" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button form="payment-form" className="button-primary">Record payment <Check size={16} /></button></>}><form id="payment-form" className="form-stack" onSubmit={submit}><div className="payment-summary"><span>Currently outstanding</span><strong>{formatINR(outstanding)}</strong><small>Partial payments are welcome. The remaining amount stays visible.</small><div className="payment-summary__breakdown"><div className="payment-summary__row"><span>Received now</span><strong>{formatINR(Math.min(enteredAmountPaise, outstanding))}</strong></div><div className="payment-summary__row"><span>Still outstanding after</span><strong>{formatINR(remainingAfter)}</strong></div></div>{enteredAmountPaise > 0 && remainingAfter > 0 && <span className="status-pill status-pill--partially_kept">Partially kept</span>}</div><div className="form-grid form-grid--two"><Field label="Amount"><div className="input-prefix"><span>₹</span><input className={inputClass} inputMode="decimal" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} required /></div></Field><Field label="Date"><input className={inputClass} type="date" value={form.paidDate} onChange={(event) => setForm({ ...form, paidDate: event.target.value })} required /></Field></div><Field label="Method"><select className={inputClass} value={form.method} onChange={(event) => setForm({ ...form, method: event.target.value as PaymentMethod })}>{["UPI", "Bank transfer", "Cash", "Other"].map((method) => <option key={method} value={method}>{method}</option>)}</select></Field><Field label="Reference" hint="Optional"><input className={inputClass} value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} placeholder="e.g. UTR or note" /></Field></form></Sheet>;
}

export function FollowUpSheet({ receivable, client, state, onClose, onMarkContacted }: { receivable: Receivable; client: Client; state: DemoState; onClose: () => void; onMarkContacted: () => void }) {
  const suggestion = getSuggestion(receivable, state);
  const template = messageTemplates[suggestion];
  const [message, setMessage] = useState(() => interpolateMessage(template, { name: client.name.split(" ")[0], amount: formatINR(getOutstanding(receivable, state.payments)), title: receivable.title, date: formatDate(getLatestPromise(receivable.id, state.promises)?.promisedDate ?? receivable.dueDate) }));
  const waUrl = client.phone ? `https://wa.me/${client.phone.replace(/\D/g, "")}?text=${encodeURIComponent(message)}` : null;
  function copyMessage() { navigator.clipboard?.writeText(message); toast.success("Message copied", { description: "Edit it further in WhatsApp if you need to." }); }
  return <Sheet title="Choose the next message" eyebrow={`${client.company} · ${suggestion === "repeated" ? "Repeated broken promise" : suggestion === "broken" ? "Broken promise" : suggestion === "partial" ? "Partial payment" : "Overdue"}`} onClose={onClose} footer={<><button className="button-secondary" onClick={copyMessage}><Copy size={15} />Copy message</button>{waUrl ? <a className="button-primary" href={waUrl} target="_blank" rel="noreferrer" onClick={onMarkContacted}><MessageCircle size={16} />Open WhatsApp</a> : <button className="button-primary" onClick={onMarkContacted}><MessageCircle size={16} />Mark contacted</button>}</>}><div className="message-tone"><div className="tone-mark"><MessageCircle size={17} /></div><div><strong>{suggestion === "repeated" ? "Repeated broken promise" : suggestion === "broken" ? "Broken promise" : suggestion === "partial" ? "Partial payment" : "Friendly overdue"}</strong><span>Editable, respectful, and never sent automatically.</span></div></div><label className="field"><span>Message preview <em>Click Open WhatsApp only when it feels right.</em></span><textarea className={`${inputClass} textarea message-editor`} value={message} onChange={(event) => setMessage(event.target.value)} rows={8} /></label><div className="message-footer"><span><ShieldCheck size={14} />You stay in control of Send.</span><button className="text-button" onClick={onMarkContacted}>Mark as contacted <Check size={14} /></button></div></Sheet>;
}

export function SnoozeSheet({ onClose, onSubmit }: { onClose: () => void; onSubmit: (until: string) => void }) {
  const [until, setUntil] = useState(() => addIndiaBusinessDays(todayInIndia(), 1));
  function submit(event: FormEvent) { event.preventDefault(); if (until < todayInIndia()) { toast.error("Choose today or a future date."); return; } onSubmit(until); }
  return <Sheet title="Snooze follow-up" eyebrow="Keep it out of sight, not out of the story" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button form="snooze-form" className="button-primary">Save snooze <Check size={16} /></button></>}><form id="snooze-form" className="form-stack" onSubmit={submit}><p className="sheet-intro">DueWeave records the pause in the private timeline. It never sends anything for you.</p><Field label="Bring this back on"><input className={inputClass} type="date" min={todayInIndia()} value={until} onChange={(event) => setUntil(event.target.value)} required /></Field></form></Sheet>;
}

export function UpgradeSheet({ onClose }: { onClose: () => void }) {
  return <Sheet title="Founder access" eyebrow="A calm way to keep the whole thread" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Maybe later</button><button className="button-ink" onClick={() => { toast.info("Real UPI activation is intentionally not connected.", { description: "This Stage 1 prototype only validates the upgrade story." }); onClose(); }}>Preview ₹499 access <ArrowUpRight size={15} /></button></>}><div className="founder-sheet"><div className="founder-sheet__price"><span>Founder Lifetime</span><strong>{formatINR(BRAND.founderPricePaise)}</strong><small>one-time · first 50 users</small></div><ul>{["Unlimited active receivables", "Complete promise history", "Advanced queue explanations", "Client reliability after enough history", "Exports and a Founder badge"].map((benefit) => <li key={benefit}><Check size={15} />{benefit}</li>)}</ul><div className="founder-note"><ShieldCheck size={16} /><span>No payment is taken here. Manual UPI activation comes after prototype validation.</span></div></div></Sheet>;
}
